/api/*  https://www.metaweather.com/api/:splat  200


[[redirects]]
  from = "api/location/search/?query=santiago"
  to = "https://www.metaweather.com/api/location/search/?query=santiago"
  status = 200
  force = true

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
